name: Documentation

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
        fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: extractions/setup-just@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Conda Deps
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: anaconda-client-env
          environment-file: ./environment.yml
      - name: Install Dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          just install
      - name: Generate Docs
        run: |
          just generate-docs
          touch docs/_build/.nojekyll
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_build/
