name: Test and Lint

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup MiniConda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        channels: readdy/label/dev,conda-forge
    - name: Install Conda Deps
      shell: bash -l {0}
      run: |
        conda install readdy
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest simularium_models_util/tests/
    - name: Upload codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup MiniConda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
        channels: readdy/label/dev,conda-forge
    - name: Install Conda Deps
      shell: bash -l {0}
      run: |
        conda install readdy
    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        flake8 simularium_models_util --count --verbose --show-source --statistics
    - name: Check with black
      shell: bash -l {0}
      run: |
        black --check simularium_models_util
